# Generated by Django 3.2.20 on 2023-08-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_remove_profile_activation_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER')], default=3, max_length=50),
            preserve_default=False,
        ),
    ]
